package com.jwt.model;
// Generated Mar 25, 2021 1:16:22 PM by Hibernate Tools 5.2.3.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * PswWsmsgs generated by hbm2java
 */
@Entity
@Table(name = "PSW_WSMSGS")
public class PswWsmsgs implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -4570819263100881433L;
	private String msgid;
	private String msgName;
	private String msgDesc;
	private String exposedBy;
	private String consumedBy;
	private String methodCode;

	public PswWsmsgs() {
	}

	public PswWsmsgs(String msgid, String msgName, String msgDesc, String exposedBy, String consumedBy) {
		this.msgid = msgid;
		this.msgName = msgName;
		this.msgDesc = msgDesc;
		this.exposedBy = exposedBy;
		this.consumedBy = consumedBy;
	}

	public PswWsmsgs(String msgid, String msgName, String msgDesc, String exposedBy, String consumedBy,
			String methodCode) {
		this.msgid = msgid;
		this.msgName = msgName;
		this.msgDesc = msgDesc;
		this.exposedBy = exposedBy;
		this.consumedBy = consumedBy;
		this.methodCode = methodCode;
	}

	@Id

	@Column(name = "MSGID", unique = true, nullable = false, length = 8)
	public String getMsgid() {
		return this.msgid;
	}

	public void setMsgid(String msgid) {
		this.msgid = msgid;
	}

	@Column(name = "MSG_NAME", nullable = false, length = 100)
	public String getMsgName() {
		return this.msgName;
	}

	public void setMsgName(String msgName) {
		this.msgName = msgName;
	}

	@Column(name = "MSG_DESC", nullable = false, length = 500)
	public String getMsgDesc() {
		return this.msgDesc;
	}

	public void setMsgDesc(String msgDesc) {
		this.msgDesc = msgDesc;
	}

	@Column(name = "EXPOSED_BY", nullable = false, length = 3)
	public String getExposedBy() {
		return this.exposedBy;
	}

	public void setExposedBy(String exposedBy) {
		this.exposedBy = exposedBy;
	}

	@Column(name = "CONSUMED_BY", nullable = false, length = 3)
	public String getConsumedBy() {
		return this.consumedBy;
	}

	public void setConsumedBy(String consumedBy) {
		this.consumedBy = consumedBy;
	}

	@Column(name = "METHOD_PROCESS_ID", length = 4)
	public String getMethodCode() {
		return this.methodCode;
	}

	public void setMethodCode(String methodCode) {
		this.methodCode = methodCode;
	}

}
